recipe_based_shopping_list/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from shopping_list_app import views
from shopping_list_app.forms import UserLoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home-page'),
    path('register/', views.SignUpView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                authentication_form=UserLoginForm,
                                                next_page='home-page'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('recipe/list/', views.RecipeListView.as_view(), name='recipe-list'),
    path('recipe/details/<int:recipe_id>/', views.RecipeDetailsView.as_view(), name='recipe-details'),
    path('recipe/create/', views.RecipeCreateView.as_view(), name='recipe-create'),
    path('recipe/delete/<int:pk>/', views.RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipe/update/<int:recipe_id>/', views.RecipeUpdateView.as_view(), name='recipe-update'),
    path('ingredient/create/', views.IndependentIngredientCreateView.as_view(), name='ingredient-create'),
    path('ingredient/list/', views.IndependentIngredientListView.as_view(), name='ingredient-list'),
    path('ingredient/delete/<int:pk>/', views.IndependentIngredientDeleteView.as_view(), name='ingredient-delete'),
    path('ingredient/update/<int:ingredient_id>/', views.IndependentIngredientUpdateView.as_view(), name='ingredient-update'),
    path('shopping-list/list/', views.ShoppingListView.as_view(), name='shoppinglist-list'),
    path('shopping-list/create/', views.ShoppingListCreateView.as_view(), name='shoppinglist-create'),
    path('shopping-list/details/<int:shopping_list_id>/', views.ShoppingListDetails.as_view(), name='shoppinglist-details'),
    path('shopping-list/delete/<int:pk>/', views.ShoppingListDeleteView.as_view(), name='shoppinglist-delete'),
]

shopping_list_app/models.py
from django.contrib.auth.models import User
from django.db import models


UNITS = (
    ('g', 'gram'),
    ('ml', 'milliliter'),
    ('pc', 'piece'),
    ('tsp', 'teaspoon'),
    ('tbsp', 'tablespoon'),
    ('pinch', 'pinch'),
    ('btl', 'bottle')
)

CATEGORIES = (
    ('bakery and bread', ' bakery and bread'),
    ('meat and seafood', 'meat and seafood'),
    ('pasta and rice', 'pasta and rice'),
    ('oils and sauces', 'oils and sauces'),
    ('dairy and eggs', 'dairy and eggs'),
    ('fruits', 'fruits'),
    ('vegetables', 'vegetables'),
    ('spices', 'spices'),
    ('other', 'other')
)


class Recipe(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(blank=True, null=True, max_length=300)
    link = models.CharField(max_length=300, null=True, blank=True)
    portions = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def no_of_ingredients(self):
        return self.ingredients.count()


class Ingredient(models.Model):
    name = models.CharField(max_length=64)
    quantity = models.FloatField(max_length=6)
    unit = models.CharField(choices=UNITS, default='g')
    category = models.CharField(choices=CATEGORIES, default='other')
    recipe = models.ForeignKey(Recipe, related_name='ingredients', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_formatted_quantity(self):
        if self.quantity % 1 == 0:
            return str(int(self.quantity))
        else:
            return str(self.quantity)


class IndependentIngredient(models.Model):
    name = models.CharField(max_length=64)
    quantity = models.FloatField(max_length=6)
    unit = models.CharField(choices=UNITS, default='pc')
    category = models.CharField(choices=CATEGORIES, default='other')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.get_formatted_quantity()} {self.unit})"

    def get_formatted_quantity(self):
        if self.quantity % 1 == 0:
            return str(int(self.quantity))
        else:
            return str(self.quantity)


class ShoppingList(models.Model):
    name = models.CharField(max_length=128, default='Shopping list')
    recipes = models.ManyToManyField(Recipe)
    independent_ingredients = models.ManyToManyField(IndependentIngredient, blank=True)
    creation_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

templates/shopping_list/shopping_list_create.html
{% extends 'base.html' %}

{% block title %} Create shopping list {% endblock %}

{% load crispy_forms_tags %}
{%  block content %}
    <div class="card">
        <h1>Create new shopping list</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Create shopping list">
        </form>
    </div>
{% endblock %}

templates/shopping_list/shopping_list_details.html
{% extends 'base.html' %}

{% block title %} Shopping list details {% endblock %}

{%  block content %}
    <style>
        .active {
            text-decoration: none;
        }

        .bought {
            text-decoration: line-through;
        }
    </style>

    <div class="card">
        <h1 class="mx-auto"> {{ shopping_list.name }}</h1>
        <p class="mx-auto">( {{ shopping_list.creation_date|date:"d.m.Y" }} )</p>
        <h3>Ingredients:</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Ingredient</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>Category</th>
                        <th>Bought</th>
                    </tr>
                </thead>
                <tbody>
                    <td class="font-weight-bold" colspan="6" style="text-align:center; background-color: #F8F0E5">Recipes ingredients</td>
                    {% for ingredient in ingredient_list %}
                        <tr id="ingredient{{ forloop.counter }}" data-list-id="{{ shopping_list.id }}" style="background-color: #F8F0E5">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ ingredient.name }}</td>
                            <td>{{ ingredient.get_formatted_quantity }}</td>
                            <td>{{ ingredient.unit }}</td>
                            <td>{{ ingredient.category }}</td>
                            <td>
                                <button class="ingredient-bought btn btn-primary" type="button">X</button>
                            </td>
                        </tr>
                    {% endfor %}
                    <td class="font-weight-bold" colspan="6" style="text-align:center; background-color: #F8F0E5">Other ingredients</td>
                    {% for independent_ingredient in independent_ingredients %}
                        <tr id="ingredient{{ forloop.counter }}" data-list-id="{{ shopping_list.id }}" style="background-color: #F8F0E5">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ independent_ingredient.name }}</td>
                            <td>{{ independent_ingredient.get_formatted_quantity }}</td>
                            <td>{{ independent_ingredient.unit }}</td>
                            <td>{{ independent_ingredient.category }}</td>
                            <td>
                                <button class="ingredient-bought btn btn-primary" type="button">X</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        <form method="POST" action="{% url 'shoppinglist-delete' pk=shopping_list.id %}">
            {% csrf_token %}
            <div class="text-center" >
                <input class="btn btn-primary" type="submit" value="Delete shopping list">
            </div>
        </form>
        <div class="text-center" >
            <a class="btn btn-primary" href="{% url 'shoppinglist-list' %}" style="margin-top: 10px">Back</a>
        </div>
    </div>

    <script>
        let boughtIngredientButtons = document.querySelectorAll(".ingredient-bought");

        boughtIngredientButtons.forEach(button => {
            let listElement = button.closest("tr");
            let listElementId = listElement.getAttribute("data-list-id");
            let className = localStorage.getItem(`shoppingList_${listElementId}_${listElement.id}`);

            if (className) {
                listElement.className = className;
            }

            button.addEventListener("click", function () {
                let listElement = this.closest("tr");
                let className = listElement.getAttribute("class");

                if (className === "bought") {
                    listElement.className = "active";
                } else {
                    listElement.className = "bought";
                }

                localStorage.setItem(`shoppingList_${listElementId}_${listElement.id}`, listElement.className);
            });
        });

        document.addEventListener("DOMContentLoaded", function() {
            boughtIngredientButtons.forEach(button => {
                let listElement = button.closest("tr");
                let listElementId = listElement.getAttribute("data-list-id");
                let savedClassName = localStorage.getItem(`shoppingList_${listElementId}_${listElement.id}`);

                if (savedClassName) {
                    listElement.className = savedClassName;
                }
            });
        });
    </script>
{% endblock %}

templates/shopping_list/shopping_list_list.html
{% extends 'base.html' %}

{% block title %} Shopping lists {% endblock %}

{%  block content %}
    {% if not shopping_lists %}
        <div class="card" style="margin-bottom: 15px">
            You don't have any shopping lists yet.
        </div>
    {% else %}
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Shopping list</th>
                <th>Creation date</th>
                <th>Actions</th>
                    </tr>
            </thead>
            <tbody>
            {% for shopping_list in shopping_lists %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ shopping_list.name }}</td>
                    <td>{{ shopping_list.creation_date|date:"d.m.Y" }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'shoppinglist-details' shopping_list_id=shopping_list.id %}">View</a>
                        <form method="POST" action="{% url 'shoppinglist-delete' pk=shopping_list.id %}" style="display: inline-block;">
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Delete">
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    <div class="text-center">
        <a class="btn btn-primary" href="{% url 'shoppinglist-create' %}">Create shopping list</a>
    </div>
{% endblock %}